name: Java CI with Maven with Windows and Mac

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [macos-latest, windows-latest]
       java-version: [8, 11]
       exclude:
        - os: macos-latest
          java-version: 11
        

    name: Build with Java 8 on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }} 8
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn verify
      working-directory: inventorymanger