name: Java CI with Maven with Windows and Mac

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # test against several OSes:
        os: [macos-latest, windows-latest]

    name: Build with Java 11 on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn verify
      working-directory: inventorymanger